env:
# - GHCVER=7.6.1
# - GHCVER=7.6.2
# - GHCVER=7.6.3
# - GHCVER=7.8.1
 - GHCVER=7.8.2
# - GHCVER=head

matrix:
  allow_failures:
    - env: GHCVER=head

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/1.18/bin:$PATH

install:
 - cabal update
 - git clone http://github.com/y-kamiya/hpc-coveralls.git
 - cd hpc-coveralls
 - cabal sandbox init
 - cabal install --bindir=$HOME/.cabal/bin/
 - cabal sandbox delete
 - cd ..
 - cabal install --only-dependencies --enable-tests 

script:
 - cabal configure --enable-tests -v2 --enable-library-coverage  # -v2 provides useful information for debugging
 - cabal build   # this builds all libraries and executables (including tests/benchmarks)
 - run-cabal-test
 - hpc-coveralls --exclude-dir=test test-hpc-coveralls-test
